"""Add user relationship and reps_per_interval to SnatchWorkout

Revision ID: 753ef62573ab
Revises: 29e0bb155ad9
Create Date: 2025-06-15 18:02:32.894758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '753ef62573ab'
down_revision = '29e0bb155ad9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snatch_workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('reps_per_interval', sa.Integer(), nullable=False, server_default='0'))
        batch_op.create_foreign_key("fk_snatch_workout_user_id", 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snatch_workout', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('reps_per_interval')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
