"""Initial migration - create snatch_workout table

Revision ID: c9dba4a66bca
Revises: 
Create Date: 2025-05-25 09:51:52.496302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9dba4a66bca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snatch_workout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_date', sa.Date(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('kettlebell_weight_kg', sa.Float(), nullable=False),
    sa.Column('total_snatches', sa.Integer(), nullable=False),
    sa.Column('total_weight_moved_kg', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snatch_workout')
    # ### end Alembic commands ###
